bloki_resztkowe/urls.py
app_name = 'bloki_resztkowe'

from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('wprowadz/', views.wprowadz_blok, name='wprowadz_blok'),
    path('nesting/new', views.nowy_nesting, name='nowy_nesting'),
    path('nesting/done', views.zakonczenie_nestingu, name='zakonczenie_nestingu'),
    path('pobierz/', views.pobierz_blok, name='pobierz_blok'),
    path('zaplanuj/', views.zaplanuj, name='zaplanuj'),
    path('<str:typ_zadania>/<str:pianka>', views.wybor, name='wybor'),
    path('', views.index, name='index'),
]

src/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('bloki_resztkowe.urls', namespace='bloki_resztkowe')),
]

bloki_resztkowe/models.py
from django.db import models
from django.utils import timezone

# Create your models here.
class Pianka(models.Model):
    typ = models.CharField(max_length=10)
    kolor = models.CharField(max_length=10)
    
    def __str__(self):
        return self.typ

    class Meta:
        db_table = ''
        managed = True
        verbose_name = 'Pianka'
        verbose_name_plural = 'Piankas'


class Nesting(models.Model):    
    pianka = models.ForeignKey(Pianka, on_delete="CASCADE")
    data_dodania = models.DateTimeField(blank=False, auto_now_add=True)
    data_zatwierdzenia = models.DateTimeField(blank=True, null=True, default=None)
    data_zakonczenia = models.DateTimeField(blank=True, null=True, default=None)
    barcode = models.CharField(max_length=50, blank=True)
    zatwierdzony = models.BooleanField(default=False)
    zakonczony = models.BooleanField(default=False)
    x = models.FloatField()
    y = models.FloatField()
    z = models.FloatField()
    
    def zatwierdz(self):
        self.zatwierdzony = True
        self.data_zatwierdzenia = timezone.now()
        self.save()
        return True

    def zakoncz(self):
        self.zakonczony = True
        self.data_zakonczenia = timezone.now()
        self.save()
        return True
    
    def __str__(self):
        zlaczenie = (str(x) for x in (self.pianka, self.x, self.y, self.z))
        return_string = " / ".join(zlaczenie)
        return return_string

    class Meta:
        db_table = ''
        managed = True
        verbose_name = 'Nesting'
        verbose_name_plural = 'Nestings'

class Errorlog(models.Model):
    error = models.TextField()
    transakcja = models.CharField(max_length=50)
    data = models.DateTimeField(auto_now=False, auto_now_add=False)
    def __str__(self):
        pass

    class Meta:
        db_table = ''
        managed = True
        verbose_name = 'Errorlog'
        verbose_name_plural = 'Errorlogs'

bloki_resztkowe/views.py
from django.shortcuts import render
from .models import *
from django.http.response import JsonResponse, HttpResponse

# Create your views here.
def index(request):
    return render(request, 'bloki_resztkowe/index.html', {})

def pobierz_blok(request):
    wpisy = {
        'typ_zadania': 'pobierz',
        'rodzaje_pianki': Pianka.objects.all(),
    }
    return render(request, 'bloki_resztkowe/wybierz_blok.html', wpisy)

def wprowadz_blok(request):
    wpisy = {
        'typ_zadania': 'Wprowadz',
        'rodzaje_pianki': Pianka.objects.all(),
    }
    return render(request, 'bloki_resztkowe/wybierz_blok.html', wpisy)

def nowy_nesting(request):
    if request.POST:
        nesting_id = request.POST.get('nesting_id', None)
        wybrany = Nesting.objects.get(id=nesting_id)
        wybrany.zatwierdz()
        return HttpResponse()


def zakonczenie_nestingu(request):
    if request.POST:
        nesting_id = request.POST.get('nesting_id', None)
        wybrany = Nesting.objects.get(id=nesting_id)
        wybrany.zakoncz()
        return HttpResponse()

def zaplanuj(request):
    wpisy = {}
    do_zaplanowania = Nesting.objects.filter(zatwierdzony=False).order_by('pianka__typ')
    wpisy['do_zaplanowania'] = do_zaplanowania
    wpisy['planowanie'] = True  
    wpisy['typ_zadania'] = 'Zaplanuj'
    return render(request, 'bloki_resztkowe/potwierdz.html', wpisy)

def wybor(request, typ_zadania, pianka):
    if pianka == 'wszystkie':
        wpisy = {
            'wybrany_wymiar': 'Wszystkie',
            'typ_zadania': typ_zadania,        
        }
        zaplanowane = Nesting.objects.filter(zatwierdzony=True, zakonczony=False).order_by('pianka__typ')
        do_zaplanowania = Nesting.objects.filter(zatwierdzony=False).order_by('pianka__typ')
        wpisy['do_zaplanowania'] = do_zaplanowania        
        wpisy['zaplanowane'] = zaplanowane        
        wpisy['pobieranie'] = True
        return render(request, 'bloki_resztkowe/potwierdz.html', wpisy)

    wybrana_pianka = Pianka.objects.get(typ=pianka)
    wpisy = {
        'wybrany_wymiar': wybrana_pianka,
        'typ_zadania': typ_zadania,        
    }
    if typ_zadania == "pobierz":        
        zaplanowane = Nesting.objects.filter(pianka=wybrana_pianka, zatwierdzony=True, zakonczony=False)
        if wybrana_pianka == 'wszystkie':
            zaplanowane = Nesting.objects.filter(zatwierdzony=True, zakonczony=False).order_by('pianka__typ')
        wpisy['zaplanowane'] = zaplanowane        
        wpisy['pobieranie'] = True
        return render(request, 'bloki_resztkowe/potwierdz.html', wpisy)
    elif typ_zadania == "wprowadz":
        if request.POST:
            x = request.POST.get('x_value', False)
            y = request.POST.get('y_value', False)
            z = request.POST.get('z_value', False)
            try:
                float(x)
                float(y)
                float(z)
                Nesting.objects.create(
                pianka = wybrana_pianka,
                x = x,
                y = y,
                z = z,
                )
            except Exception as e:
                error = {
                    'message': "Błąd: " + str(e),
                    'color': "red"
                }
                print(e)
                wpisy = {
                    'wybrany_wymiar': wybrana_pianka,
                    'typ_zadania': typ_zadania,
                    'error': error
                }
                return render(request, 'bloki_resztkowe/wprowadz_wymiar.html', wpisy)            
            error = {
                'message': "Nesting dodany!",
                'color': "green"
            }
            wpisy['error'] = error
            return render(request, 'bloki_resztkowe/wprowadz_wymiar.html', wpisy)
        return render(request, 'bloki_resztkowe/wprowadz_wymiar.html', wpisy)

bloki_resztkowe/templates/bloki_resztkowe/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Bloki resztkowe{% endblock title %}</title>
    <link rel="stylesheet" href="{% static '/bloki_resztkowe/assets/bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Amatic+SC">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Archivo+Black">
    <link rel="stylesheet" href="{% static 'bloki_resztkowe/assets/css/styles.css' %}">
</head>

<body>
    
    {% block header %}
    <div class="row">
        <div class="col-lg-4 col-lg-offset-4 col-md-12">
            <div>
                <a href="{% url 'bloki_resztkowe:index' %}">
                <h1 class="text-center" style="font-style:normal;font-family:'Archivo Black', sans-serif;">BLOKI RESZTKOWE</h1>
                </a>
            </div>
        </div>
        <div class="col-md-12">
            <div>
                <hr>
            </div>
        </div>
    </div>
    {% endblock header %}
        
    {% block body %}{% endblock body %}
    <script src="{% static 'bloki_resztkowe/assets/js/jquery.min.js' %}"></script>
    <script src="{% static 'bloki_resztkowe/assets/bootstrap/js/bootstrap.min.js' %}"></script>    
    {% block jquery %}
    <script src="{% static 'bloki_resztkowe/assets/bootstrap/js/scripts.js' %}"></script>
    {% endblock jquery %} 
</body>

</html>

bloki_resztkowe/templates/bloki_resztkowe/index.html
<!DOCTYPE html>
{% extends 'bloki_resztkowe/base.html' %}


{% block body %}
<div class="container">
  <div class="row">
      <div class="col-lg-12 col-lg-offset-0 col-md-12">
          <div style="height:76px;"></div>
      </div>
  </div>
  <div class="row">
    <a href="{% url 'bloki_resztkowe:wprowadz_blok'  %}">
      <div class="col-xs-8 col-xs-offset-2" style="background-color:#70ad47;">
          <h2 class="text-center" style="font-style:normal;" id="blok-resztkowy">Wprowadź blok resztkowy</h2>
      </div>
    </a>
  </div>
  <div class="row">
      <div class="col-lg-12 col-lg-offset-0 col-md-12">
          <div style="height:76px;"></div>
      </div>
  </div>
  <div class="row">
    <a href="{% url 'bloki_resztkowe:pobierz_blok'  %}">
      <div class="col-lg-8 col-md-8 col-sm-8 col-xs-8 col-xs-offset-2" style="background-color:#ff3300;">
          <h2 class="text-center" style="font-style:normal;">Pobierz blok resztkowy</h2>
      </div>
    </a>
  </div>
</div>
{% endblock body %}

{% block jquery %}

{% endblock jquery %}

bloki_resztkowe/templates/bloki_resztkowe/potwierdz.html
<!DOCTYPE html>
{% extends 'bloki_resztkowe/base.html' %}

{% block body %}
<div class="row">
    <div class="col-md-12" style="background-color:#70ad47;">
        <h2 class="text-center">{{ typ_zadania|title }} blok resztkowy</h2>
    </div>
</div>
<div class="row" style="padding:10px;"></div>
<div class="row">
    <div class="col-md-12" style="background-color:#{{ wybrany_wymiar.kolor }};">
        <h3 class="text-center">{{ wybrany_wymiar.typ }}</h3>
    </div>
</div>
<div class="row" style="padding:10px;">
    {% if pobieranie %}               
    <div class="col-lg-6">
        <h2 class="text-center">Zaplanowane</h2>
        <div class="table-responsive">
            <table class="table table-hover table-striped">
                <thead>
                    <tr>
                        <th class="text-center">LP.</th>
                        <th class="text-center">Zaplanowane</th>
                        {% if wybrany_wymiar == 'Wszystkie' %}
                            <th >Typ pianki</th>                                
                        {% endif %}
                        <th class="text-center"></th>
                    </tr>
                </thead>
                <tbody>
                    {% for wpis in zaplanowane %}                      
                        <tr class="text-center">
                            <td>{{ forloop.counter }}</td>
                            <td>{{ wpis.x|floatformat }} / {{ wpis.y|floatformat }} / {{ wpis.z|floatformat }}</td>
                            
                            {% if wybrany_wymiar == 'Wszystkie' %}
                                <td style="background-color: #{{ wpis.pianka.kolor }}">{{ wpis.pianka.typ }}</td>                                
                            {% endif %}
                            
                            <td><i class="glyphicon glyphicon-ok ok-sign-done" style="font-size:24px;font-weight:normal;color:#70ad47;" data-id="{{ wpis.id }}"></i></td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
    <div class="col-lg-6">        
        <h2 class="text-center">Do zaplanowania</h2>
        <div class="table-responsive">
            <table class="table table-hover table-striped">
                <thead>
                    <tr class="text-center">
                        <th class="text-center">LP.</th>
                        <th class="text-center">Do zaplanowania</th>
                        <th class="text-center">Typ pianki</th>
                    </tr>
                </thead>
                <tbody>
                    {% for wpis in do_zaplanowania %}                      
                    <tr class="text-center">
                        <td>{{ forloop.counter }}</td>
                        <td>{{ wpis.x|floatformat }} / {{ wpis.y|floatformat }} / {{ wpis.z|floatformat }}</td>
                        <td style="background-color: #{{ wpis.pianka.kolor }}">{{ wpis.pianka.typ }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
    {% endif %}
    
    {% if planowanie %}      
    <div class="col-lg-12">        
        <h2 class="text-center">Do zaplanowania</h2>
        <div class="table-responsive">
            <table class="table table-hover table-striped">
                <thead>
                    <tr class="text-center">
                        <th class="text-center">LP.</th>
                        <th class="text-center">Do zaplanowania</th>
                        <th class="text-center">Typ pianki</th>
                        <th class="text-center"></th>
                    </tr>
                </thead>
                <tbody>
                    {% for wpis in do_zaplanowania %}                      
                    <tr class="text-center">
                        <td>{{ forloop.counter }}</td>
                        <td>{{ wpis.x|floatformat }} / {{ wpis.y|floatformat }} / {{ wpis.z|floatformat }}</td>
                        <td style="background-color: #{{ wpis.pianka.kolor }}">{{ wpis.pianka.typ }}</td>
                        <td><i class="glyphicon glyphicon-ok ok-sign-todo" style="font-size:24px;font-weight:normal;color:#70ad47;" data-id="{{ wpis.id }}"></i></td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
    {% endif %}
</div>

{% if not planowanie %}
<div class="row">
    <a href="/{{ typ_zadania }}">
        <div class="col-md-4 col-md-offset-4 col-xs-10 col-xs-offset-1" style="background-color:#ffffff;">
            <button type="button" class="btn btn-danger btn-block">Cofnij</button>
        </div>
    </a>
</div>
{% endif %}
{% endblock body %}


{% block jquery %}
    <script>
            $(document).ready(function () {
                $('.ok-sign-todo').click(function (e) { 
                    e.preventDefault();
                    var ok = $(this)
                    $.ajax({
                        type: "post",
                        url: "{% url 'bloki_resztkowe:nowy_nesting' %}",
                        data: {
                            'nesting_id': ok.attr('data-id'),
                            'csrfmiddlewaretoken': '{{ csrf_token }}'
                        },
                        dataType: "html",
                        success: function (response) {
                            ok.closest('tr').fadeOut();
                        }           
                    });
                    location.reload();
                });
                
                $('.ok-sign-done').click(function (e) { 
                    e.preventDefault();
                    var ok_done = $(this)
                    $.ajax({
                        type: "post",
                        url: "{% url 'bloki_resztkowe:zakonczenie_nestingu' %}",
                        data: {
                            'nesting_id': ok_done.attr('data-id'),
                            'csrfmiddlewaretoken': '{{ csrf_token }}'
                        },
                        dataType: "html",
                        success: function (response) {
                            ok_done.closest('tr').fadeOut();
                        }           
                    });
                    location.reload();
                });
            });      
    </script>
{% endblock jquery %}
    

bloki_resztkowe/templates/bloki_resztkowe/wprowadz_wymiar.html
<!DOCTYPE html>
{% extends 'bloki_resztkowe/base.html' %}

{% block body %}
    <div class="row">
        <div class="col-md-12" style="background-color:#70ad47;">
            <h2 class="text-center">{{ typ_zadania|title }} blok resztkowy</h2>
        </div>
    </div>
    <div class="row" style="padding:10px;"></div>
    <div class="row">
        <div class="col-md-12" style="background-color:#70ad47;">
            <h3 class="text-center">Podaj wymiar bloku:</h3>
        </div>
    </div>
    <div class="row" style="padding:10px;"></div>  
        <div class="row">
            <div class="col-xs-4 col-xs-offset-4" style="background-color:#{{ wybrany_wymiar.kolor }};margin-bottom:5px;">
                <h3 class="text-center">{{ wybrany_wymiar.typ }}</h3>
            </div>
        </div>
        <div class="row" style="margin:20px;"></div>

        <form action="{% url 'bloki_resztkowe:wybor' typ_zadania wybrany_wymiar.typ %}" method="POST" id="wymiary">
        {% csrf_token %}
        <div class="row">
            <div class="col-md-4 col-md-offset-4 col-xs-10 col-xs-offset-1" style="margin-bottom:5px;">
                <div class="row pagination-centered">
                    <div class="col-xs-2">
                        <h1>X=</h1>
                    </div>
                    <div class="col-xs-10" style="background-color:#ffff00;"><input type="number" name="x_value" placeholder="........................." class="text-center" style="width:100%;height:50px;margin-top:10px;margin-bottom:10px;"></div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-4 col-md-offset-4 col-xs-10 col-xs-offset-1" style="margin-bottom:5px;">
                <div class="row pagination-centered">
                    <div class="col-xs-2">
                        <h1>Y=</h1>
                    </div>
                    <div class="col-xs-10" style="background-color:#ffff00;"><input type="number" name="y_value" placeholder="........................." class="text-center" style="width:100%;height:50px;margin-top:10px;margin-bottom:10px;"></div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-4 col-md-offset-4 col-xs-10 col-xs-offset-1" style="margin-bottom:5px;">
                <div class="row pagination-centered">
                    <div class="col-xs-2">
                        <h1>Z=</h1>
                    </div>
                    <div class="col-xs-10" style="background-color:#ffff00;"><input type="number" name="z_value" placeholder="........................." class="text-center" style="width:100%;height:50px;margin-top:10px;margin-bottom:10px;"></div>
                </div>
            </div>
        </div>
        <div class="row" style="margin:20px;"></div>
        <div class="row">
            <div class="col-xs-4 col-xs-offset-4 text-center" id="btn-save">
                <button class="btn btn-success btn-primary btn-block" type="submit" value="submit" form="wymiary">ZATWIERDŹ</button>                                
            </div>
        </div>
    </form>
    <div class="row" style="margin:20px;"></div>
    <div class="row">
        <a href="/{{ typ_zadania }}">
            <div class="col-md-4 col-md-offset-4 col-xs-10 col-xs-offset-1" style="background-color:#ffffff;">
                <button type="button" class="btn btn-danger btn-block">Cofnij</button>
            </div>
        </a>
    </div>
    <div class="row text-center">
            <div class="col-md-4 col-md-offset-4 col-xs-10 col-xs-offset-1" style="background-color:#ffffff;">
                <p style="color: {{ error.color }};">{{ error.message }}</p>
            </div>
        </div>
{% endblock body %}

bloki_resztkowe/templates/bloki_resztkowe/wybierz_blok.html
<!DOCTYPE html>
{% extends 'bloki_resztkowe/base.html' %}

{% block body %} 
<div class="row">
    <div class="col-md-12" style="background-color:#70ad47;">
        <h2 class="text-center">{{ typ_zadania|title }} blok resztkowy</h2>
    </div>
</div>
<div class="row" style="padding:10px;"></div>
<div class="row">
    <div class="col-md-12" style="background-color:#70ad47;">
        <h3 class="text-center">Wybierz rodzaj pianki</h3>
    </div>
</div>
<div class="row" style="padding:10px;"></div>
{% for row in rodzaje_pianki %}
    <div class="row">
        <a href="{% url 'bloki_resztkowe:wybor' typ_zadania|lower row.typ %}">
        <div class="col-md-4 col-md-offset-4 col-xs-10 col-xs-offset-1" style="background-color:#{{row.kolor}};margin-bottom:5px;">
            <h3 class="text-center">{{ row.typ }}</h3>
        </div>
        </a>
    </div>  
{% endfor %}

{% if typ_zadania == 'pobierz' %}
    <div class="row">
        <a href="{% url 'bloki_resztkowe:wybor' typ_zadania|lower 'wszystkie' %}">
            <div class="col-md-4 col-md-offset-4 col-xs-10 col-xs-offset-1" style="background: color #5a2311;;margin-bottom:5px;">
                <h3 class="text-center">Wszystkie</h3>
            </div>
        </a>
    </div> 
{% endif %}
<hr>
<div class="row">
    <a href="{% url 'bloki_resztkowe:index' %}">
        <div class="col-md-4 col-md-offset-4 col-xs-10 col-xs-offset-1" style="background-color:#ffffff;">
                <button type="button" class="btn btn-danger btn-block">Cofnij</button>
        </div>
    </a>
</div>
{% endblock body%}